// <auto-generated />
using LibrosAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrosAPI.Migrations
{
    [DbContext(typeof(LibrosDbContext))]
    [Migration("20260828003404_Migracion-Inicial3")]
    partial class MigracionInicial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrosAPI.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 1967,
                            Autor = "Gabriel García Márquez",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 1605,
                            Autor = "Miguel de Cervantes",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 1985,
                            Autor = "Gabriel García Márquez",
                            Titulo = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            Id = 4,
                            AnioPublicacion = 1992,
                            Autor = "Barrett Kaman",
                            Titulo = "Flexidy"
                        },
                        new
                        {
                            Id = 5,
                            AnioPublicacion = 1992,
                            Autor = "Perkin Kinkaid",
                            Titulo = "Tampflex"
                        },
                        new
                        {
                            Id = 6,
                            AnioPublicacion = 2011,
                            Autor = "Kyle Cowpe",
                            Titulo = "It"
                        },
                        new
                        {
                            Id = 7,
                            AnioPublicacion = 1993,
                            Autor = "Alfonse Kempson",
                            Titulo = "Bitwolf"
                        },
                        new
                        {
                            Id = 8,
                            AnioPublicacion = 2001,
                            Autor = "Lucia Pettinger",
                            Titulo = "Cardify"
                        },
                        new
                        {
                            Id = 9,
                            AnioPublicacion = 1994,
                            Autor = "Aldous Paty",
                            Titulo = "Bytecard"
                        },
                        new
                        {
                            Id = 10,
                            AnioPublicacion = 1997,
                            Autor = "Blair Leisman",
                            Titulo = "Redhold"
                        },
                        new
                        {
                            Id = 11,
                            AnioPublicacion = 2006,
                            Autor = "Adolphus Sneezum",
                            Titulo = "Matsoft"
                        },
                        new
                        {
                            Id = 12,
                            AnioPublicacion = 2011,
                            Autor = "Gualterio Teare",
                            Titulo = "Cardify"
                        },
                        new
                        {
                            Id = 13,
                            AnioPublicacion = 1997,
                            Autor = "Laverna Tuffs",
                            Titulo = "Subin"
                        },
                        new
                        {
                            Id = 14,
                            AnioPublicacion = 2005,
                            Autor = "Heath Rosier",
                            Titulo = "Duobam"
                        },
                        new
                        {
                            Id = 15,
                            AnioPublicacion = 2003,
                            Autor = "Darsie Biggam",
                            Titulo = "Rank"
                        },
                        new
                        {
                            Id = 16,
                            AnioPublicacion = 1995,
                            Autor = "Babara Jayme",
                            Titulo = "Cardify"
                        },
                        new
                        {
                            Id = 17,
                            AnioPublicacion = 2012,
                            Autor = "Izak Kingswoode",
                            Titulo = "Zaam-Dox"
                        },
                        new
                        {
                            Id = 18,
                            AnioPublicacion = 1995,
                            Autor = "Francine Brownbill",
                            Titulo = "Bigtax"
                        },
                        new
                        {
                            Id = 19,
                            AnioPublicacion = 2012,
                            Autor = "Donielle Monckton",
                            Titulo = "Tin"
                        },
                        new
                        {
                            Id = 20,
                            AnioPublicacion = 2000,
                            Autor = "Pavlov Shuttell",
                            Titulo = "Treeflex"
                        },
                        new
                        {
                            Id = 21,
                            AnioPublicacion = 2009,
                            Autor = "Moria Konmann",
                            Titulo = "Pannier"
                        },
                        new
                        {
                            Id = 22,
                            AnioPublicacion = 2012,
                            Autor = "Imelda Hartup",
                            Titulo = "Zathin"
                        },
                        new
                        {
                            Id = 23,
                            AnioPublicacion = 1997,
                            Autor = "Mitzi Rudkin",
                            Titulo = "Zaam-Dox"
                        },
                        new
                        {
                            Id = 24,
                            AnioPublicacion = 2009,
                            Autor = "Editha Piesing",
                            Titulo = "Biodex"
                        },
                        new
                        {
                            Id = 25,
                            AnioPublicacion = 1987,
                            Autor = "Ariella Leftley",
                            Titulo = "Fixflex"
                        },
                        new
                        {
                            Id = 26,
                            AnioPublicacion = 1999,
                            Autor = "Esme Felstead",
                            Titulo = "Subin"
                        },
                        new
                        {
                            Id = 27,
                            AnioPublicacion = 1989,
                            Autor = "Alethea Clayhill",
                            Titulo = "Latlux"
                        },
                        new
                        {
                            Id = 28,
                            AnioPublicacion = 2004,
                            Autor = "Nicoli Millott",
                            Titulo = "Fixflex"
                        },
                        new
                        {
                            Id = 29,
                            AnioPublicacion = 1995,
                            Autor = "Vanny Guyon",
                            Titulo = "Fintone"
                        },
                        new
                        {
                            Id = 30,
                            AnioPublicacion = 1995,
                            Autor = "Ebenezer Teml",
                            Titulo = "Tres-Zap"
                        },
                        new
                        {
                            Id = 31,
                            AnioPublicacion = 1984,
                            Autor = "Siusan Mathewson",
                            Titulo = "Quo Lux"
                        },
                        new
                        {
                            Id = 32,
                            AnioPublicacion = 2010,
                            Autor = "Agatha Bunn",
                            Titulo = "Bamity"
                        },
                        new
                        {
                            Id = 33,
                            AnioPublicacion = 2008,
                            Autor = "Kaylyn Villa",
                            Titulo = "Duobam"
                        },
                        new
                        {
                            Id = 34,
                            AnioPublicacion = 2007,
                            Autor = "Nelson Ingerfield",
                            Titulo = "Temp"
                        },
                        new
                        {
                            Id = 35,
                            AnioPublicacion = 2012,
                            Autor = "Van Charopen",
                            Titulo = "Transcof"
                        },
                        new
                        {
                            Id = 36,
                            AnioPublicacion = 2001,
                            Autor = "Mariele Bentley",
                            Titulo = "Latlux"
                        },
                        new
                        {
                            Id = 37,
                            AnioPublicacion = 1987,
                            Autor = "Dione Robarts",
                            Titulo = "Span"
                        },
                        new
                        {
                            Id = 38,
                            AnioPublicacion = 1994,
                            Autor = "Selma Ovitts",
                            Titulo = "Zoolab"
                        },
                        new
                        {
                            Id = 39,
                            AnioPublicacion = 2009,
                            Autor = "Hayyim Gilks",
                            Titulo = "Bigtax"
                        },
                        new
                        {
                            Id = 40,
                            AnioPublicacion = 2001,
                            Autor = "Bronnie Huygen",
                            Titulo = "Mat Lam Tam"
                        },
                        new
                        {
                            Id = 41,
                            AnioPublicacion = 1989,
                            Autor = "Cindra Postan",
                            Titulo = "Bamity"
                        },
                        new
                        {
                            Id = 42,
                            AnioPublicacion = 2008,
                            Autor = "Clea Vasilyev",
                            Titulo = "Zaam-Dox"
                        },
                        new
                        {
                            Id = 43,
                            AnioPublicacion = 1993,
                            Autor = "Emerson Pape",
                            Titulo = "Keylex"
                        },
                        new
                        {
                            Id = 44,
                            AnioPublicacion = 2010,
                            Autor = "Vanny Peepall",
                            Titulo = "Zontrax"
                        },
                        new
                        {
                            Id = 45,
                            AnioPublicacion = 2001,
                            Autor = "Carlen MacSkeagan",
                            Titulo = "Tampflex"
                        },
                        new
                        {
                            Id = 46,
                            AnioPublicacion = 2000,
                            Autor = "Nessi Mattisssen",
                            Titulo = "Pannier"
                        },
                        new
                        {
                            Id = 47,
                            AnioPublicacion = 1995,
                            Autor = "Jose Twiggins",
                            Titulo = "Domainer"
                        },
                        new
                        {
                            Id = 48,
                            AnioPublicacion = 2003,
                            Autor = "Corbett Colqueran",
                            Titulo = "Zaam-Dox"
                        },
                        new
                        {
                            Id = 49,
                            AnioPublicacion = 2004,
                            Autor = "Alene Ayris",
                            Titulo = "Matsoft"
                        },
                        new
                        {
                            Id = 50,
                            AnioPublicacion = 1998,
                            Autor = "Joceline Tancock",
                            Titulo = "Bamity"
                        },
                        new
                        {
                            Id = 51,
                            AnioPublicacion = 1998,
                            Autor = "Fred Prisk",
                            Titulo = "It"
                        },
                        new
                        {
                            Id = 52,
                            AnioPublicacion = 2011,
                            Autor = "Dexter Beggs",
                            Titulo = "Toughjoyfax"
                        },
                        new
                        {
                            Id = 53,
                            AnioPublicacion = 2005,
                            Autor = "Lorrie Tolossi",
                            Titulo = "Veribet"
                        },
                        new
                        {
                            Id = 54,
                            AnioPublicacion = 2007,
                            Autor = "Lucita Ebbutt",
                            Titulo = "Redhold"
                        },
                        new
                        {
                            Id = 55,
                            AnioPublicacion = 2006,
                            Autor = "Ignacio Casswell",
                            Titulo = "Treeflex"
                        },
                        new
                        {
                            Id = 56,
                            AnioPublicacion = 2009,
                            Autor = "Thedrick Abeau",
                            Titulo = "Wrapsafe"
                        },
                        new
                        {
                            Id = 57,
                            AnioPublicacion = 2003,
                            Autor = "Delbert MacGowan",
                            Titulo = "Cookley"
                        },
                        new
                        {
                            Id = 58,
                            AnioPublicacion = 2006,
                            Autor = "Carmela Frowen",
                            Titulo = "Overhold"
                        },
                        new
                        {
                            Id = 59,
                            AnioPublicacion = 2003,
                            Autor = "Eberhard Goldhawk",
                            Titulo = "Zamit"
                        },
                        new
                        {
                            Id = 60,
                            AnioPublicacion = 1994,
                            Autor = "Editha Cristol",
                            Titulo = "Mat Lam Tam"
                        },
                        new
                        {
                            Id = 61,
                            AnioPublicacion = 2005,
                            Autor = "Arin Genney",
                            Titulo = "Greenlam"
                        },
                        new
                        {
                            Id = 62,
                            AnioPublicacion = 1988,
                            Autor = "Titos Stranahan",
                            Titulo = "Bytecard"
                        },
                        new
                        {
                            Id = 63,
                            AnioPublicacion = 1993,
                            Autor = "Allissa Billington",
                            Titulo = "Zaam-Dox"
                        },
                        new
                        {
                            Id = 64,
                            AnioPublicacion = 2006,
                            Autor = "Ezmeralda O' Ronan",
                            Titulo = "Transcof"
                        },
                        new
                        {
                            Id = 65,
                            AnioPublicacion = 2000,
                            Autor = "Darla Laidler",
                            Titulo = "Duobam"
                        },
                        new
                        {
                            Id = 66,
                            AnioPublicacion = 2009,
                            Autor = "Joice Taffee",
                            Titulo = "Stim"
                        },
                        new
                        {
                            Id = 67,
                            AnioPublicacion = 2013,
                            Autor = "Candi Herion",
                            Titulo = "Zamit"
                        },
                        new
                        {
                            Id = 68,
                            AnioPublicacion = 2010,
                            Autor = "Nicolai Cornil",
                            Titulo = "Greenlam"
                        },
                        new
                        {
                            Id = 69,
                            AnioPublicacion = 1996,
                            Autor = "Emmye Tyrie",
                            Titulo = "Subin"
                        },
                        new
                        {
                            Id = 70,
                            AnioPublicacion = 2010,
                            Autor = "Obed Philippart",
                            Titulo = "Fintone"
                        },
                        new
                        {
                            Id = 71,
                            AnioPublicacion = 1994,
                            Autor = "Linnea Stiff",
                            Titulo = "Ronstring"
                        },
                        new
                        {
                            Id = 72,
                            AnioPublicacion = 1997,
                            Autor = "Axe Bartlomiej",
                            Titulo = "Asoka"
                        },
                        new
                        {
                            Id = 73,
                            AnioPublicacion = 2006,
                            Autor = "Carline Jedrachowicz",
                            Titulo = "Ronstring"
                        },
                        new
                        {
                            Id = 74,
                            AnioPublicacion = 2008,
                            Autor = "Merell Halsall",
                            Titulo = "Konklab"
                        },
                        new
                        {
                            Id = 75,
                            AnioPublicacion = 2002,
                            Autor = "Domenic Britcher",
                            Titulo = "Pannier"
                        },
                        new
                        {
                            Id = 76,
                            AnioPublicacion = 2008,
                            Autor = "Darn Jacmard",
                            Titulo = "Zamit"
                        },
                        new
                        {
                            Id = 77,
                            AnioPublicacion = 1988,
                            Autor = "Hillard Larsen",
                            Titulo = "Span"
                        },
                        new
                        {
                            Id = 78,
                            AnioPublicacion = 2009,
                            Autor = "Fabien Iacobucci",
                            Titulo = "Fix San"
                        },
                        new
                        {
                            Id = 79,
                            AnioPublicacion = 2000,
                            Autor = "Sauncho O'Leahy",
                            Titulo = "Duobam"
                        },
                        new
                        {
                            Id = 80,
                            AnioPublicacion = 2000,
                            Autor = "Padriac Colbridge",
                            Titulo = "Andalax"
                        },
                        new
                        {
                            Id = 81,
                            AnioPublicacion = 1996,
                            Autor = "Lynsey Scutching",
                            Titulo = "Zoolab"
                        },
                        new
                        {
                            Id = 82,
                            AnioPublicacion = 1984,
                            Autor = "Christos Cantopher",
                            Titulo = "Zamit"
                        },
                        new
                        {
                            Id = 83,
                            AnioPublicacion = 1987,
                            Autor = "Charil Stoacley",
                            Titulo = "Wrapsafe"
                        },
                        new
                        {
                            Id = 84,
                            AnioPublicacion = 2013,
                            Autor = "Maggi Lydiate",
                            Titulo = "Toughjoyfax"
                        },
                        new
                        {
                            Id = 85,
                            AnioPublicacion = 1993,
                            Autor = "Guido Humber",
                            Titulo = "Aerified"
                        },
                        new
                        {
                            Id = 86,
                            AnioPublicacion = 2010,
                            Autor = "Amitie Harston",
                            Titulo = "Lotstring"
                        },
                        new
                        {
                            Id = 87,
                            AnioPublicacion = 2006,
                            Autor = "Kimmie Shippey",
                            Titulo = "Voyatouch"
                        },
                        new
                        {
                            Id = 88,
                            AnioPublicacion = 2008,
                            Autor = "Theobald Sprosson",
                            Titulo = "Viva"
                        },
                        new
                        {
                            Id = 89,
                            AnioPublicacion = 2006,
                            Autor = "Jorge Ayerst",
                            Titulo = "Ventosanzap"
                        },
                        new
                        {
                            Id = 90,
                            AnioPublicacion = 1993,
                            Autor = "Elyn Bercevelo",
                            Titulo = "Fix San"
                        },
                        new
                        {
                            Id = 91,
                            AnioPublicacion = 1996,
                            Autor = "Cary Colam",
                            Titulo = "Viva"
                        },
                        new
                        {
                            Id = 92,
                            AnioPublicacion = 1989,
                            Autor = "Iorgos Tonepohl",
                            Titulo = "Aerified"
                        },
                        new
                        {
                            Id = 93,
                            AnioPublicacion = 1999,
                            Autor = "Otho Huntington",
                            Titulo = "Flexidy"
                        },
                        new
                        {
                            Id = 94,
                            AnioPublicacion = 1995,
                            Autor = "Gwenni Robard",
                            Titulo = "Duobam"
                        },
                        new
                        {
                            Id = 95,
                            AnioPublicacion = 1954,
                            Autor = "Floyd Powlesland",
                            Titulo = "Trippledex"
                        },
                        new
                        {
                            Id = 96,
                            AnioPublicacion = 2004,
                            Autor = "Reginauld Ragdale",
                            Titulo = "Aerified"
                        },
                        new
                        {
                            Id = 97,
                            AnioPublicacion = 2004,
                            Autor = "Arel Abeau",
                            Titulo = "Kanlam"
                        },
                        new
                        {
                            Id = 98,
                            AnioPublicacion = 1984,
                            Autor = "Jacinthe Barnshaw",
                            Titulo = "Zamit"
                        },
                        new
                        {
                            Id = 99,
                            AnioPublicacion = 1994,
                            Autor = "Ramsay Stenners",
                            Titulo = "Y-Solowarm"
                        },
                        new
                        {
                            Id = 100,
                            AnioPublicacion = 2003,
                            Autor = "Ferris Jandl",
                            Titulo = "Hatity"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
