// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculosAPI.Models;

#nullable disable

namespace VehiculosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910235101_Migrcion_Inicial")]
    partial class Migrcion_Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehiculosAPI.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chevrolet"
                        });
                });

            modelBuilder.Entity("VehiculosAPI.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarcaId = 1,
                            Nombre = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            MarcaId = 1,
                            Nombre = "Hilux"
                        },
                        new
                        {
                            Id = 3,
                            MarcaId = 2,
                            Nombre = "Civic"
                        },
                        new
                        {
                            Id = 4,
                            MarcaId = 2,
                            Nombre = "CR-V"
                        },
                        new
                        {
                            Id = 5,
                            MarcaId = 3,
                            Nombre = "Mustang"
                        },
                        new
                        {
                            Id = 6,
                            MarcaId = 3,
                            Nombre = "Ranger"
                        },
                        new
                        {
                            Id = 7,
                            MarcaId = 4,
                            Nombre = "Camaro"
                        },
                        new
                        {
                            Id = 8,
                            MarcaId = 4,
                            Nombre = "Silverado"
                        });
                });

            modelBuilder.Entity("VehiculosAPI.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2020,
                            ModeloId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2022,
                            ModeloId = 1
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2021,
                            ModeloId = 2
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2019,
                            ModeloId = 3
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2023,
                            ModeloId = 3
                        },
                        new
                        {
                            Id = 6,
                            Anio = 2022,
                            ModeloId = 4
                        },
                        new
                        {
                            Id = 7,
                            Anio = 2021,
                            ModeloId = 5
                        },
                        new
                        {
                            Id = 8,
                            Anio = 2020,
                            ModeloId = 6
                        },
                        new
                        {
                            Id = 9,
                            Anio = 2018,
                            ModeloId = 7
                        },
                        new
                        {
                            Id = 10,
                            Anio = 2023,
                            ModeloId = 8
                        });
                });

            modelBuilder.Entity("VehiculosAPI.Models.Modelo", b =>
                {
                    b.HasOne("VehiculosAPI.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("VehiculosAPI.Models.Vehiculo", b =>
                {
                    b.HasOne("VehiculosAPI.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("VehiculosAPI.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("VehiculosAPI.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
